### ISSUE TITLE
Allow running robotpy at root in src layout project

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-cli#4]
Previously one would've been able to run `python src/robot.py sim` at the project root, and things would have mostly worked.

We should make it just as easy to specify scripts in a Pipfile or poetry/pdm pyproject.toml with the new CLI.

**Comment by virtuald** [comment]
You can do `python -m robotpy --main src/robot.py sim`

**Comment by auscompgeek** [comment]
Ah, good point. We should probably just do the right thing here anyway.
